apiVersion: apps/v1 # which api to use for deployment
kind: Deployment # what kind of service/object do you want to create?

# what would you like to call it - name the service/object

metadata:
  name: nginx-deployment
spec:
  selector: 
    matchLabels:
      app: nginx
  replicas: 3

  template:
    metadata:
      labels:
        app: nginx
    
    spec: 
      containers:
      - name: nginx
        image: marix1993/tech221-nginx:v2
        ports:
        - containerPort: 80