---
apiVersion: v1
kind: Service

metadata:
  name: nginx-svc
  namespace: default #sre 

spec:
  ports:
  - nodePort: 30001 # range is 30000-32768
    port: 80

    targetPort: 80

  selector:
    app: nginx # this label connects this servie to deployment
    
  type: NodePort # also use LoadBalancer - for local cluster
  